### PR TITLE
fix: Removes generated id from factory in favor of DB

### LINKED ISSUE #144: remove `id` from factories in favor of database generation

### PR DESCRIPTION
**Pull request by mthomps4**
## Changes
fix: Removes generated id from factory in favor of DB

## Checklist
- [x] Generating a new app works

Fixes #144

### CODE REVIEW

**Comment by kgajera** [comment]
Should we also remove it from our `UserFactory`?

I think it will also cleanup this line and allow us to remove the eslint disable: https://github.com/echobind/bisonapp/blob/canary/packages/create-bison-app/template/tests/requests/user/signup.test.ts#L94

**Comment by mthomps4** [comment]
> Should we also remove it from our `UserFactory`?
> 
> I think it will also cleanup this line and allow us to remove the eslint disable: https://github.com/echobind/bisonapp/blob/canary/packages/create-bison-app/template/tests/requests/user/signup.test.ts#L94

Yup, 
I'll make a note to clean that up. Forgot about the pre-existing pieces. 👍🏼

**Review by kgajera — COMMENTED** [review]
Ran `yarn test` in a new bison app and the signup test is failing:

Screen Shot 2021-07-01 at 10 17 53 AM

**Comment by mthomps4** [comment]
@kgajera Thanks for double-checking that! 
I removed `roles` previously from unused linting - and that was needing to be stripped for the test. 👍🏼 

---

Also, didn't realize UserFactory was still using the old custom Attrs instead of built types -- corrected that as well. 
```
Partial<Prisma.UserCreateInput> 
```


4fd8459

**Review by kgajera — APPROVED** [review]

**Pull request merged**
