### PR TITLE
fix: remove nexus build from build script

### LINKED ISSUE #72: generated build command should not include `nexus dev`
This was missed in #68.

### PR DESCRIPTION
**Pull request by cball**
This was missed in #68. Additionally, we needed a few additional build scripts to ensure a proper production build.

## Changes

- add nexus, next, and prisma build scripts to ensure a proper production build.

## Screenshots

n/a

## Checklist

- [ ] Requires dependency update?
- [x] Generating a new app works

Fixes #72

### CODE REVIEW

**Review by mcavaliere — COMMENTED** [review]
@cball Generated an app from this release and it started successfully, but getting the following: 

image

**Comment by cball** [comment]
@mcavaliere looks like you might be using an older release? the build command should be https://github.com/echobind/bisonapp/pull/74/files#diff-399b2acbf24e192838a40ee0f8fe44e0R9

also the "get used plugins" line is from Nexus Framework, which we just converted to @nexus/schema.

**Review by isaiahgrey93 — APPROVED** [review]

**Comment by cball** [comment]
reconfirmed locally as well.

**Comment by mcavaliere** [comment]
@cball correct, I had to unlink and relink. New error when generating: 

image

**Pull request merged**
